### ISSUE TITLE
Cannot compile Firefox for whatever reason.

### ISSUE THREAD

**Issue by ghost** [rust9x/rust#27]
Hello, there! I've been trying to compile Luminafox (my Firefox fork targeting Windows XP, Vista, 7 & 8.1) using rust9x, but sadly it refuses to compile and throws out an error in the Rust toolchain checks. Any fix would be appreciated.
![image](https://github.com/rust9x/rust/assets/167991948/808b145a-f981-466a-a5f5-4048f2e87082)

**Comment by yuztra** [comment]
for clarification: the dev(s) forgot to include cargo in rust9x, so please include it in the next update of rust9x.
