### ISSUE TITLE
Reimplement `fileextd.lib` fallbacks in rust

### ISSUE THREAD

**Issue by seritools** [rust9x/rust#43]
Would allow more/most `GetFileInformationByHandleEx`/`SetFileInformationByHandle` to succeed on NT-based systems, while still falling back properly on 9x.

**Comment by cher-nov** [comment]
Some additional info just for clarity:

https://web.archive.org/web/20121018011132/http://www.microsoft.com/en-us/download/details.aspx?id=22599
(old link: http://www.microsoft.com/downloads/details.aspx?FamilyID=1DECC547-AB00-4963-A360-E4130EC079B8&displaylang=en - unfortunately not preserved in Wayback Machine, _may God bless 'em_)

**Win32 FileID API Library** - Additional kernel APIs for specific functionality.
This library contains functions for accessing file information based on ID (`OpenFileByID`, `GetFileInformationByHandleEx`, and `SetFileInformationByHandle`).

_File Name:_ Win32 FileID APIs 1.1.EXE  
_Version:_ 1.1  
_Date Published:_ 10/3/2006

https://web.archive.org/web/20061124104838/https://download.microsoft.com/download/0/f/e/0fe2a777-5ac5-40d1-8700-86169b182eda/Win32%20FileID%20APIs%201.1.EXE

Mirrors (in Russian) + DLL version of the library:
https://oktava-studio.ru/fileextd.php
https://hex.pp.ua/fileextd.php - same link, but on another domain

**Comment by seritools** [comment]
fileextd.lib is also still part of current Windows SDKs. Including it however wouldn't work well with the runtime detection in rust9x

**Comment by seritools** [comment]
correction - modern winsdk still has fileextd.lib, but does not include the `GetFileInformationByHandleEx` fallback anymore it seems. The one in the Win7 SDK does, however: `C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Lib\fileextd.lib`

**Comment by seritools** [comment]
Implemented in [rust9x-1.84-beta-v3](https://github.com/rust9x/rust/releases/tag/rust9x-1.84-beta-v3)
