### ISSUE TITLE
Build rust9x as `rustc`?

### ISSUE THREAD

**Issue by roytam1** [rust9x/rust#7]
I wonder if it is possible to build rust9x as `rustc` (i.e. same executable name as vanilla rust)?

**Comment by seritools** [comment]
(sorry for the late reply, my notification settings were wrong)

Yes, it builds just like the regular rustc, just with the additional targets provided. If you follow https://github.com/rust9x/rust/wiki#compiling-the-compiler-and-standard-library it should do just that.

Let me know if you encounter any issues, I'd be glad to help!

EDIT: Oh hey, I've used your browser forks a few times on WinXP in the past hehe
