### ISSUE TITLE
Is it possible to make the compiler itself runnable on XP?

### ISSUE THREAD

**Issue by Thyristor-Chopper** [rust9x/rust#8]
Is it possible to make the compiler itself runnable on XP? I mean, the host OS is XP and running rustc from there.

**Comment by seritools** [comment]
Technically yes, though you'd need to patch up all crates that directly use different Windows API (outside of the standard library) that are used by rustc, and that potentially use APIs not available.

**Comment by Thyristor-Chopper** [comment]
is it ok if I share the binary of Rust9x publicly ?

(rustc.exe, rustdoc.exe, cargo.exe, and the driver files)

**Comment by seritools** [comment]
I'd appreciate if you mark it as third-party build, but otherwise sure, go ahead!

**Comment by Thyristor-Chopper** [comment]
uploaded - https://github.com/pbcairo/rust9x-compiler

**Comment by the-r3dacted** [comment]
> uploaded - https://github.com/pbcairo/rust9x-compiler

What patches did you need or what changes did you make?
