### ISSUE TITLE
Update to newer rust version

### ISSUE THREAD

**Issue by cyrex562** [rust9x/rust#9]
Is it possible to update the forked version that rust9x uses to compile to a newer version? If it's possible, what steps are necessary to do so? I've run into an issue where certain libraries require toolchain 1.64 or better in order to compile.

**Comment by seritools** [comment]
Sure, that's possible.

You'll have to rebase the rust9x branch onto the later versions, and re-port all the changes, and port/stub/workaround any new APIs added since then.

I personally don't really have the time at the moment to do that, sorry :x
But if someone was up to it I'd definitely welcome that :)

**Comment by seritools** [comment]
Also feel free to hit me up via discord if you or someone else is interested in this, I'd be glad to provide assistance.

**Comment by RandomInsano** [comment]
I’m interested but can’t dedicate the time. I think this is super cool and one day I’ll be able to make time and revisit porting some stuff back to the good old days. 😃 On Aug 29, 2023, at 7:12 AM, Dennis Duda ***@***.***> wrote:﻿
Also feel free to hit me up via discord if you or someone else is interested in this, I'd be glad to provide assistance.

**Comment by cyrex562** [comment]
Thanks! I will take a look into this and hit you up on discord with any questions.

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=Y3lyZXg1NjJAZ21haWwuY29t>

**Comment by seritools** [comment]
Update: Rust9x 1.76.0 is looking good so far! Will likely be done in the next few days.

**Comment by seritools** [comment]
Rust9x is now [updated to 1.76-beta](https://seri.tools/blog/rust9x-1-76/) 🎉

Feel free to open another issue in the future should the need for a new version arise 👍

**Comment by RandomInsano** [comment]
Nice! I've been lurking watching the issues and it's fun to see the progress rolling in. :)

**Comment by Thyristor-Chopper** [comment]
Cool, thanks
